/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springboot.gradle.crud.example;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
