/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springboot.gradle.crud.example;

import org.junit.Test;

import springboot.gradle.crud.example.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
